on:
  push:
    branches:
      - master
env:
  DEFAULT_ACCOUNT_ID: ${{ secrets.HUBSPOT_ACCOUNT_ID }}
  DEFAULT_PERSONAL_ACCESS_KEY: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install HubSpot CLI
        uses: HubSpot/hubspot-project-actions/install-hubspot-cli@v1.0.0
        with:
          cli_version: '7.6.0-beta.11'
      - name: HubSpot Project Upload Action
        uses: HubSpot/hubspot-project-actions/project-upload@v1.0.0
